(function(){tinymce.create("tinymce.plugins.IcePlugin",{deleteTag:"span",insertTag:"span",deleteClass:"del",insertClass:"ins",changeIdAttribute:"data-cid",userIdAttribute:"data-userid",userNameAttribute:"data-username",timeAttribute:"data-time",preserveOnPaste:"p",user:{name:"Unknown User",id:Math.random()},isTracking:!0,contentEditable:!0,css:"css/ice.css",manualInit:!1,scriptVersion:(new Date).getTime(),afterInit:function(){},afterClean:function(a){return a},beforePasteClean:function(a){return a},
afterPasteClean:function(a){return a},init:function(a,d){function f(){var e=a.dom.select(b.insertSelector+":empty,"+b.deleteSelector+":empty");a.dom.remove(e)}var b=this,c=null;a.onPostRender.add(function(){var e=a.dom;tinymce.extend(b,a.getParam("ice"));b.insertSelector="."+b.insertClass;b.deleteSelector="."+b.deleteClass;a.serializer.addRules(b.insertTag+"[id|class|title|"+b.changeIdAttribute+"|"+b.userIdAttribute+"|"+b.userNameAttribute+"|"+b.timeAttribute+"]");a.serializer.addRules(b.deleteTag+
"[id|class|title|"+b.changeIdAttribute+"|"+b.userIdAttribute+"|"+b.userNameAttribute+"|"+b.timeAttribute+"]");a.serializer.addRules("tempdel[data-allocation]");e.loadCSS(b.css.indexOf("://")>0?b.css:d+"/"+b.css);var c=function(){b.manualInit||a.execCommand("initializeice")},e=document.createElement("script");e.type="text/javascript";e.readyState?e.onreadystatechange=function(){c()}:e.onload=c;e.src=d+"/js/ice.min.js?version="+b.scriptVersion;document.getElementsByTagName("head")[0].appendChild(e);
a.controlManager.setActive("ice_toggleshowchanges",!0);b.isTracking&&a.controlManager.setActive("ice_togglechanges",!0)});a.addCommand("initializeice",function(e){a=e||a;tinymce.DOM.win.setTimeout(function(){c=(new ice.InlineChangeEditor({element:a.getBody(),isTracking:b.isTracking,contentEditable:b.contentEditable,changeIdAttribute:b.changeIdAttribute,userIdAttribute:b.userIdAttribute,userNameAttribute:b.userNameAttribute,timeAttribute:b.timeAttribute,currentUser:{id:b.user.id,name:b.user.name},
plugins:["IceEmdashPlugin","IceAddTitlePlugin","IceSmartQuotesPlugin",{name:"IceCopyPastePlugin",settings:{pasteType:"formattedClean",preserve:b.preserveOnPaste,beforePasteClean:b.beforePasteClean,afterPasteClean:b.afterPasteClean}}],changeTypes:{insertType:{tag:b.insertTag,alias:b.insertClass},deleteType:{tag:b.deleteTag,alias:b.deleteClass}}})).startTracking();a.onEvent.add(function(a,b){return c.handleEvent(b)});setTimeout(function(){b.afterInit.call(b)},10)},500)});a.addCommand("ice_initenv",
function(){c.initializeEnvironment();c.initializeRange()});a.addCommand("icecleanbody",function(e){return c.getCleanContent(e||a.getContent(),b.afterClean,b.beforeClean)});a.addCommand("ice_hasDeletePlaceholders",function(){return c.isPlaceholdingDeletes});a.addCommand("ice_addDeletePlaceholders",function(){return c.placeholdDeletes()});a.addCommand("ice_removeDeletePlaceholders",function(){return c.revertDeletePlaceholders()});a.addCommand("iceinsert",function(a){a=a||{};c.insert(a.item,a.range)});
a.addCommand("icedelete",function(a){a=a||{};c.deleteContents(a.right,a.range)});a.addCommand("ice_changeuser",function(a){c.setCurrentUser(a)});a.addCommand("iceaccept",function(b){a.undoManager.add();c.acceptChange(b||a.selection.getNode());f()});a.addCommand("icereject",function(b){a.undoManager.add();c.rejectChange(b||a.selection.getNode());f()});a.addCommand("iceacceptall",function(){a.undoManager.add();c.acceptAll();f()});a.addCommand("icerejectall",function(){a.undoManager.add();c.rejectAll();
f()});a.addCommand("ice_toggleshowchanges",function(){var b=a.getBody(),c=a.controlManager,d=!0;a.dom.hasClass(b,"CT-hide")?(c.setActive("ice_toggleshowchanges",!0),a.dom.removeClass(b,"CT-hide"),d=!1):(c.setActive("ice_toggleshowchanges",!1),a.dom.addClass(b,"CT-hide"));tinymce.each(["iceacceptall","icerejectall"],function(a){c.setDisabled(a,d)});a.execCommand("mceRepaint")});a.addCommand("ice_smartquotes",function(b){c.pluginsManager.plugins.IceSmartQuotesPlugin.convert(a.getBody());b||a.windowManager.alert("Regular quotes have been converted into smart quotes.")});
a.addCommand("ice_togglechanges",function(){c.isTracking?a.execCommand("ice_disable"):a.execCommand("ice_enable")});a.addCommand("ice_enable",function(){c.enableChangeTracking();a.controlManager.setActive("ice_togglechanges",!0);b.isTracking=!0});a.addCommand("ice_disable",function(){c.disableChangeTracking();a.controlManager.setActive("ice_togglechanges",!1);b.isTracking=!1});a.addCommand("ice_isTracking",function(){return c.isTracking?1:0});a.addCommand("ice_strippaste",function(a){return c.pluginsManager.plugins.IceCopyPastePlugin.stripPaste(a)});
a.addCommand("ice_handlepaste",function(){return c.pluginsManager.plugins.IceCopyPastePlugin.handlePaste()});a.addCommand("ice_handleemdash",function(){return c.pluginsManager.plugins.IceEmdashPlugin.convertEmdash()?1:0});a.addButton("iceaccept",{title:"Accept Change",image:d+"/img/accept.gif",cmd:"iceaccept"});a.addButton("icereject",{title:"Reject Change",image:d+"/img/reject.gif",cmd:"icereject"});a.addButton("iceacceptall",{title:"Accept All Changes",image:d+"/img/ice-accept.png",cmd:"iceacceptall"});
a.addButton("icerejectall",{title:"Reject All Changes",image:d+"/img/ice-reject.png",cmd:"icerejectall"});a.addButton("ice_toggleshowchanges",{title:"Show/Hide Track Changes",image:d+"/img/ice-showchanges.png",cmd:"ice_toggleshowchanges"});a.addButton("ice_smartquotes",{title:"Convert quotes to smart quotes","class":"mce_blockquote",cmd:"ice_smartquotes"});a.addButton("ice_togglechanges",{title:"Turn On Track Changes ",image:d+"/img/ice-togglechanges.png",cmd:"ice_togglechanges"});a.plugins.contextmenu&&
a.plugins.contextmenu.onContextMenu.add(function(c,d,f){a.dom.getParent(f,b.insertSelector+","+b.deleteSelector)&&(d.add({title:"Accept Change",icon:"accept",cmd:"iceaccept"}),d.add({title:"Reject Change",icon:"reject",cmd:"icereject"}))});a.onNodeChange.add(function(c,d,g){a.dom.getParent(g,b.insertSelector+","+b.deleteSelector)?(d.setDisabled("iceaccept",!1),d.setDisabled("icereject",!1)):(d.setDisabled("iceaccept",!0),d.setDisabled("icereject",!0));f()})}});tinymce.PluginManager.add("ice",tinymce.plugins.IcePlugin)})();
